Chart and location
chingu-voyages/v48-tier3-team-22 pull request #31
Opened 2024-03-19 22:37 UTC by vukas86

This pull request introduces two significant enhancements to our project: a dynamic chart, and a map in form of the jpg displaying dinosaur location where has been founded.

- The chart visualizes the diet diversity of dinosaurs, offering insights into their dietary habits. I used react-chart-js-2 library. 

- The location is represented in the map that I get using Mapbox GL JS library, I needed to do forward geolocation in order to get coordinates of the location from the name of the country and then to display location map in JPG format.

Your feedback and review are greatly appreciated.

2024-03-20 21:35 UTC, EmperorA commented
ok

2024-03-21 11:14 UTC, EmperorA requested changes
you added node_modules. you may want to remove them and compare your components with dev branch before creating a PR. there is so much conflicts.

2024-03-26 00:40 UTC, vukas86 commented
I see that by mistake I deleted .gitignore ouside the client folder and added inside the folder

2024-03-26 13:21 UTC, EmperorA approved these changes

2024-03-26 13:22 UTC, merged